name: CI/CD

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
        
      - name: MkDocs Setup
        run: pip install mkdocs mkdocs-material

      - name: Build
        run: mkdocs build
      
      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ./site
      
      - name: SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}

      - name: Deploy
        run: scp -r -P 2222 -o StrictHostKeyChecking=no ./site/* \
          ${{ secrets.HELIOS_USER }}@${{ secrets.HELIOS_URL }}:/home/studs/${{ secrets.HELIOS_USER }}/public_html/

